# Generated by Django 3.0.5 on 2020-04-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('AM', 'Automobile'), ('BT', 'Bank Transfer'), ('CW', 'Cash Withdrawal'), ('ED', 'Education'), ('EN', 'Entertainment'), ('FN', 'Fine'), ('FO', 'Food'), ('HC', 'Health Care'), ('PY', 'PayTM'), ('RG', 'Recharge'), ('SP', 'Shopping'), ('TL', 'Travel'), ('UN', 'Unknown'), ('UPI', 'UPI')], default='UN', max_length=3),
        ),
    ]
