# Generated by Django 3.0.5 on 2020-05-08 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_auto_20200423_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Automobile', 'Automobile'), ('Bank Transfer', 'Bank Transfer'), ('Cash Withdrawal', 'Cash Withdrawal'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Fine', 'Fine'), ('Food', 'Food'), ('Health Care', 'Health Care'), ('Other', 'Other'), ('Paytm', 'Paytm'), ('Recharge', 'Recharge'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('UPI', 'UPI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile', models.IntegerField(default=0)),
                ('bank', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=0)),
                ('education', models.IntegerField(default=0)),
                ('entertainment', models.IntegerField(default=0)),
                ('fine', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('paytm', models.IntegerField(default=0)),
                ('recharge', models.IntegerField(default=0)),
                ('shopping', models.IntegerField(default=0)),
                ('travel', models.IntegerField(default=0)),
                ('upi', models.IntegerField(default=0)),
                ('month', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec'), ('None', 'None')], default='None', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
