# Generated by Django 3.0.6 on 2020-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='automobile',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='bank',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cash',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='education',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='entertainment',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='fine',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='food',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='health',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='budget',
            name='other',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='paytm',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='recharge',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='shopping',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='travel',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='budget',
            name='upi',
            field=models.IntegerField(default=1000),
        ),
    ]
